/**
 * Custom component type with additional block-specific properties
 * These properties are set via defineOptions() in Vue components
 */
export type Block = Component & {
   __name: string; // The autogenerated name of the block
   props: Record<string, any>;
   id: string;
   type: string;
   // Defined in template
   label?: string;
   emoji?: string; // A single emoji character
   // fields file
   fields?: Record<string, any>;
   // Auto generated from the component path
   directory?: string; // Where the block component is located (e.g., "@page-builder/blocks/hero-section")
   // Margin
   margin?: { top?: string; bottom?: string };
};
