/**
 * Custom component type with additional layout-specific properties
 * These properties are set via defineOptions() in Vue components
 */
export type Layout = Component & {
   __name: string; // The autogenerated name of the layout
   label: string; // The custom name of the layout
   fields?: Record<string, EditorFieldConfig>;
};
